// <auto-generated />
using System;
using AllergyFinder.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AllergyFinder.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926151423_AddRestaurantsAndDishes")]
    partial class AddRestaurantsAndDishes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergyFinder.Api.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_allergens");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_allergens_code");

                    b.ToTable("allergens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GLUTEN",
                            Name = "Cereali contenenti glutine"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CRUSTACEANS",
                            Name = "Crostacei"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EGGS",
                            Name = "Uova"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FISH",
                            Name = "Pesce"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PEANUTS",
                            Name = "Arachidi"
                        },
                        new
                        {
                            Id = 6,
                            Code = "SOY",
                            Name = "Soia"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MILK",
                            Name = "Latte (incluso il lattosio)"
                        },
                        new
                        {
                            Id = 8,
                            Code = "TREE_NUTS",
                            Name = "Frutta a guscio"
                        },
                        new
                        {
                            Id = 9,
                            Code = "CELERY",
                            Name = "Sedano"
                        },
                        new
                        {
                            Id = 10,
                            Code = "MUSTARD",
                            Name = "Senape"
                        },
                        new
                        {
                            Id = 11,
                            Code = "SESAME",
                            Name = "Semi di sesamo"
                        },
                        new
                        {
                            Id = 12,
                            Code = "SULPHITES",
                            Name = "Anidride solforosa e solfiti"
                        },
                        new
                        {
                            Id = 13,
                            Code = "LUPIN",
                            Name = "Lupini"
                        },
                        new
                        {
                            Id = 14,
                            Code = "MOLLUSCS",
                            Name = "Molluschi"
                        });
                });

            modelBuilder.Entity("AllergyFinder.Api.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AllergensDeclaredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("allergens_declared_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("price");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id")
                        .HasName("pk_dishes");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_dishes_restaurant_id");

                    b.ToTable("dishes", (string)null);
                });

            modelBuilder.Entity("AllergyFinder.Api.Models.DishAllergen", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("integer")
                        .HasColumnName("dish_id");

                    b.Property<int>("AllergenId")
                        .HasColumnType("integer")
                        .HasColumnName("allergen_id");

                    b.Property<string>("Presence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("presence");

                    b.HasKey("DishId", "AllergenId")
                        .HasName("pk_dish_allergens");

                    b.HasIndex("AllergenId")
                        .HasDatabaseName("ix_dish_allergens_allergen_id");

                    b.ToTable("dish_allergens", (string)null);
                });

            modelBuilder.Entity("AllergyFinder.Api.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cuisine_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("PriceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("price_level");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.ToTable("restaurants", null, t =>
                        {
                            t.HasCheckConstraint("ck_restaurants_price_level", "price_level BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("AllergyFinder.Api.Models.Dish", b =>
                {
                    b.HasOne("AllergyFinder.Api.Models.Restaurant", "Restaurant")
                        .WithMany("Dishes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dishes_restaurants_restaurant_id");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("AllergyFinder.Api.Models.DishAllergen", b =>
                {
                    b.HasOne("AllergyFinder.Api.Models.Allergen", "Allergen")
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dish_allergens_allergens_allergen_id");

                    b.HasOne("AllergyFinder.Api.Models.Dish", "Dish")
                        .WithMany("Allergens")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dish_allergens_dishes_dish_id");

                    b.Navigation("Allergen");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("AllergyFinder.Api.Models.Dish", b =>
                {
                    b.Navigation("Allergens");
                });

            modelBuilder.Entity("AllergyFinder.Api.Models.Restaurant", b =>
                {
                    b.Navigation("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
