// <auto-generated />
using AllergyFinder.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AllergyFinder.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergyFinder.Api.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_allergens");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_allergens_code");

                    b.ToTable("allergens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GLUTEN",
                            Name = "Cereali contenenti glutine"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CRUSTACEANS",
                            Name = "Crostacei"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EGGS",
                            Name = "Uova"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FISH",
                            Name = "Pesce"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PEANUTS",
                            Name = "Arachidi"
                        },
                        new
                        {
                            Id = 6,
                            Code = "SOY",
                            Name = "Soia"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MILK",
                            Name = "Latte (incluso il lattosio)"
                        },
                        new
                        {
                            Id = 8,
                            Code = "TREE_NUTS",
                            Name = "Frutta a guscio"
                        },
                        new
                        {
                            Id = 9,
                            Code = "CELERY",
                            Name = "Sedano"
                        },
                        new
                        {
                            Id = 10,
                            Code = "MUSTARD",
                            Name = "Senape"
                        },
                        new
                        {
                            Id = 11,
                            Code = "SESAME",
                            Name = "Semi di sesamo"
                        },
                        new
                        {
                            Id = 12,
                            Code = "SULPHITES",
                            Name = "Anidride solforosa e solfiti"
                        },
                        new
                        {
                            Id = 13,
                            Code = "LUPIN",
                            Name = "Lupini"
                        },
                        new
                        {
                            Id = 14,
                            Code = "MOLLUSCS",
                            Name = "Molluschi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
